### ISSUE TITLE
Add more BlockIds & ItemIds

### ISSUE THREAD

**Issue by AgentH14** [CuongZ/UNWDelicatedSoftware#6]
could you add more More Blocks and Items please?

blocks and items such as: Birch Trapdoor, Spruce Trapdoor, Acacia, Trapdoor, and all the newest Vanilla Blocks as well please?

**Comment by dtcu0ng** [comment]
I tried to work with them, but none of them all worked. If you can, please help me by trying to add them and make a commit in the reborn-alpha branch, I will test it and bring up the branch as soon as possible.

UNWDS is a folk of PocketMine-MP, since version 2.0, I haven't modified much to its core, so feel free to touch it like what you do with PocketMine-MP.

Thanks.

**Comment by dtcu0ng** [comment]
Closed #6. You can reopen this issue in [UNWDS stable repo](https://github.com/UnnamedNetwork/UNWDS)
